#!/bin/sh

echo Enter your git user email:
read email
git config --global alias.co checkout
git config --global alias.l "!git for-each-ref --sort=-committerdate refs/remotes/ --format='%(refname:short)' | grep -v 'HEAD' | head -n 10"
git config --global user.email $email
git config --global user.name "Matej Ukmar"
