#!/bin/sh

# Fish install
mv ~/.config/fish/config.fish ~/.config/fish/config.fish.bak
ln -s ~/.config/dotfiles/fish/config.fish ~/.config/fish/config.fish

mv ~/.config/fish/functions ~/.config/fish/functions_bak
mkdir -pv ~/.config/fish/functions/
ln -s ~/.config/dotfiles/fish/functions/fish_prompt.fish ~/.config/fish/functions/fish_prompt.fish
ln -s ~/.config/dotfiles/fish/functions/fish_mode_prompt.fish ~/.config/fish/functions/fish_mode_prompt.fish
ln -s ~/.config/dotfiles/fish/functions/fish_user_key_bindings.fish ~/.config/fish/functions/fish_user_key_bindings.fish
ln -s ~/.config/dotfiles/fish/functions/fzf_key_bindings.fish ~/.config/fish/functions/fzf_key_bindings.fish

# GIT alias
git config --global alias.co checkout

# Scripts init
./init_scripts
sed -i '$a\export PATH=~/.config/dotfiles/bin:"${PATH}"' ~/.bashrc
sed -i '$a\export PATH=~/.config/dotfiles/scripts/bin:"${PATH}"' ~/.bashrc
sed -i '$a\fish' ~/.bashrc