#!/bin/sh

defaults write -g AppleShowAllFiles -bool true
killall Finder

defaults write com.apple.dock autohide-time-modifier -float 0.15
killall Dock

# Disable caps lock delay (needed for karabiner)
hidutil property --set '{"CapsLockDelayOverride":0}'
