#!/bin/sh

mv ~/Library/Application\ Support/VSCodium/User/settings.json ~/Library/Application\ Support/VSCodium/User/settings.json.bak
ln -s ~/.config/dotfiles/vscodium/settings.json ~/Library/Application\ Support/VSCodium/User/settings.json
